version: 2
updates:
- package-ecosystem: docker
  directory: "/.devcontainer"
  schedule:
    interval: daily
    time: "03:00"
  open-pull-requests-limit: 10
  reviewers:
  - tiksn
  assignees:
  - tiksn
